#include "bitmapkit/internal.h"

typedef struct bk_tag_registry_entry {
  uint32_t code;
  const char *name;
  const char *family;
  const char *use;
} bk_tag_registry_entry;

static const bk_tag_registry_entry exif_registry[] = {
    {
        0x0100u,
        "ImageWidth",
        "TIFF",
        "metadata",
    },
    {
        0x0101u,
        "ImageLength",
        "TIFF",
        "metadata",
    },
    {
        0x0102u,
        "BitsPerSample",
        "TIFF",
        "metadata",
    },
    {
        0x0103u,
        "Compression",
        "TIFF",
        "metadata",
    },
    {
        0x0106u,
        "PhotometricInterpretation",
        "TIFF",
        "metadata",
    },
    {
        0x010eu,
        "ImageDescription",
        "TIFF",
        "metadata",
    },
    {
        0x010fu,
        "Make",
        "TIFF",
        "metadata",
    },
    {
        0x0110u,
        "Model",
        "TIFF",
        "metadata",
    },
    {
        0x0111u,
        "StripOffsets",
        "TIFF",
        "metadata",
    },
    {
        0x0112u,
        "Orientation",
        "TIFF",
        "metadata",
    },
    {
        0x0115u,
        "SamplesPerPixel",
        "TIFF",
        "metadata",
    },
    {
        0x0116u,
        "RowsPerStrip",
        "TIFF",
        "metadata",
    },
    {
        0x0117u,
        "StripByteCounts",
        "TIFF",
        "metadata",
    },
    {
        0x011au,
        "XResolution",
        "TIFF",
        "metadata",
    },
    {
        0x011bu,
        "YResolution",
        "TIFF",
        "metadata",
    },
    {
        0x011cu,
        "PlanarConfiguration",
        "TIFF",
        "metadata",
    },
    {
        0x0128u,
        "ResolutionUnit",
        "TIFF",
        "metadata",
    },
    {
        0x0131u,
        "Software",
        "TIFF",
        "metadata",
    },
    {
        0x0132u,
        "DateTime",
        "TIFF",
        "metadata",
    },
    {
        0x013bu,
        "Artist",
        "TIFF",
        "metadata",
    },
    {
        0x013eu,
        "WhitePoint",
        "TIFF",
        "metadata",
    },
    {
        0x013fu,
        "PrimaryChromaticities",
        "TIFF",
        "metadata",
    },
    {
        0x014au,
        "SubIFDs",
        "TIFF",
        "metadata",
    },
    {
        0x0156u,
        "TransferRange",
        "TIFF",
        "metadata",
    },
    {
        0x0201u,
        "JPEGInterchangeFormat",
        "TIFF",
        "metadata",
    },
    {
        0x0202u,
        "JPEGInterchangeFormatLength",
        "TIFF",
        "metadata",
    },
    {
        0x0211u,
        "YCbCrCoefficients",
        "TIFF",
        "metadata",
    },
    {
        0x0212u,
        "YCbCrSubSampling",
        "TIFF",
        "metadata",
    },
    {
        0x0213u,
        "YCbCrPositioning",
        "TIFF",
        "metadata",
    },
    {
        0x0214u,
        "ReferenceBlackWhite",
        "TIFF",
        "metadata",
    },
    {
        0x8298u,
        "Copyright",
        "TIFF",
        "metadata",
    },
    {
        0x829au,
        "ExposureTime",
        "Exif",
        "metadata",
    },
    {
        0x829du,
        "FNumber",
        "Exif",
        "metadata",
    },
    {
        0x8769u,
        "ExifIFDPointer",
        "Exif",
        "metadata",
    },
    {
        0x8822u,
        "ExposureProgram",
        "Exif",
        "metadata",
    },
    {
        0x8827u,
        "ISOSpeedRatings",
        "Exif",
        "metadata",
    },
    {
        0x9000u,
        "ExifVersion",
        "Exif",
        "metadata",
    },
    {
        0x9003u,
        "DateTimeOriginal",
        "Exif",
        "metadata",
    },
    {
        0x9004u,
        "DateTimeDigitized",
        "Exif",
        "metadata",
    },
    {
        0x9101u,
        "ComponentsConfiguration",
        "Exif",
        "metadata",
    },
    {
        0x9102u,
        "CompressedBitsPerPixel",
        "Exif",
        "metadata",
    },
    {
        0x9201u,
        "ShutterSpeedValue",
        "Exif",
        "metadata",
    },
    {
        0x9202u,
        "ApertureValue",
        "Exif",
        "metadata",
    },
    {
        0x9203u,
        "BrightnessValue",
        "Exif",
        "metadata",
    },
    {
        0x9204u,
        "ExposureBiasValue",
        "Exif",
        "metadata",
    },
    {
        0x9205u,
        "MaxApertureValue",
        "Exif",
        "metadata",
    },
    {
        0x9206u,
        "SubjectDistance",
        "Exif",
        "metadata",
    },
    {
        0x9207u,
        "MeteringMode",
        "Exif",
        "metadata",
    },
    {
        0x9208u,
        "LightSource",
        "Exif",
        "metadata",
    },
    {
        0x9209u,
        "Flash",
        "Exif",
        "metadata",
    },
    {
        0x920au,
        "FocalLength",
        "Exif",
        "metadata",
    },
    {
        0x927cu,
        "MakerNote",
        "Exif",
        "metadata",
    },
    {
        0x9286u,
        "UserComment",
        "Exif",
        "metadata",
    },
    {
        0xa000u,
        "FlashpixVersion",
        "Exif",
        "metadata",
    },
    {
        0xa001u,
        "ColorSpace",
        "Exif",
        "metadata",
    },
    {
        0xa002u,
        "PixelXDimension",
        "Exif",
        "metadata",
    },
    {
        0xa003u,
        "PixelYDimension",
        "Exif",
        "metadata",
    },
    {
        0xa005u,
        "InteroperabilityIFDPointer",
        "Exif",
        "metadata",
    },
    {
        0xa20bu,
        "FlashEnergy",
        "Exif",
        "metadata",
    },
    {
        0xa20eu,
        "FocalPlaneXResolution",
        "Exif",
        "metadata",
    },
    {
        0xa20fu,
        "FocalPlaneYResolution",
        "Exif",
        "metadata",
    },
    {
        0xa210u,
        "FocalPlaneResolutionUnit",
        "Exif",
        "metadata",
    },
    {
        0xa217u,
        "SensingMethod",
        "Exif",
        "metadata",
    },
    {
        0xa300u,
        "FileSource",
        "Exif",
        "metadata",
    },
    {
        0xa301u,
        "SceneType",
        "Exif",
        "metadata",
    },
    {
        0xa302u,
        "CFAPattern",
        "Exif",
        "metadata",
    },
    {
        0xa401u,
        "CustomRendered",
        "Exif",
        "metadata",
    },
    {
        0xa402u,
        "ExposureMode",
        "Exif",
        "metadata",
    },
    {
        0xa403u,
        "WhiteBalance",
        "Exif",
        "metadata",
    },
    {
        0xa404u,
        "DigitalZoomRatio",
        "Exif",
        "metadata",
    },
    {
        0xa405u,
        "FocalLengthIn35mmFilm",
        "Exif",
        "metadata",
    },
    {
        0xa406u,
        "SceneCaptureType",
        "Exif",
        "metadata",
    },
    {
        0xa407u,
        "GainControl",
        "Exif",
        "metadata",
    },
    {
        0xa408u,
        "Contrast",
        "Exif",
        "metadata",
    },
    {
        0xa409u,
        "Saturation",
        "Exif",
        "metadata",
    },
    {
        0xa40au,
        "Sharpness",
        "Exif",
        "metadata",
    },
    {
        0xa40cu,
        "SubjectDistanceRange",
        "Exif",
        "metadata",
    },
};

static const bk_tag_registry_entry photoshop_registry[] = {
    {
        1000u,
        "ChannelsRowsColumnsDepthMode",
        "Photoshop",
        "image-resource",
    },
    {
        1001u,
        "MacPrintInfo",
        "Photoshop",
        "image-resource",
    },
    {
        1002u,
        "XMLData",
        "Photoshop",
        "image-resource",
    },
    {
        1003u,
        "IndexedColorTable",
        "Photoshop",
        "image-resource",
    },
    {
        1005u,
        "ResolutionInfo",
        "Photoshop",
        "image-resource",
    },
    {
        1006u,
        "NamesOfAlphaChannels",
        "Photoshop",
        "image-resource",
    },
    {
        1007u,
        "DisplayInfo",
        "Photoshop",
        "image-resource",
    },
    {
        1008u,
        "Caption",
        "Photoshop",
        "image-resource",
    },
    {
        1009u,
        "BorderInformation",
        "Photoshop",
        "image-resource",
    },
    {
        1010u,
        "BackgroundColor",
        "Photoshop",
        "image-resource",
    },
    {
        1011u,
        "PrintFlags",
        "Photoshop",
        "image-resource",
    },
    {
        1012u,
        "GrayscaleHalftoning",
        "Photoshop",
        "image-resource",
    },
    {
        1013u,
        "ColorHalftoning",
        "Photoshop",
        "image-resource",
    },
    {
        1014u,
        "DuotoneHalftoning",
        "Photoshop",
        "image-resource",
    },
    {
        1015u,
        "GrayscaleTransfer",
        "Photoshop",
        "image-resource",
    },
    {
        1016u,
        "ColorTransfer",
        "Photoshop",
        "image-resource",
    },
    {
        1017u,
        "DuotoneTransfer",
        "Photoshop",
        "image-resource",
    },
    {
        1018u,
        "DuotoneImageInfo",
        "Photoshop",
        "image-resource",
    },
    {
        1019u,
        "EffectiveBlackWhite",
        "Photoshop",
        "image-resource",
    },
    {
        1021u,
        "EPSOptions",
        "Photoshop",
        "image-resource",
    },
    {
        1022u,
        "QuickMaskInfo",
        "Photoshop",
        "image-resource",
    },
    {
        1024u,
        "LayerStateInfo",
        "Photoshop",
        "image-resource",
    },
    {
        1025u,
        "WorkingPath",
        "Photoshop",
        "image-resource",
    },
    {
        1026u,
        "LayersGroupInfo",
        "Photoshop",
        "image-resource",
    },
    {
        1028u,
        "IPTC",
        "Photoshop",
        "image-resource",
    },
    {
        1029u,
        "ImageModeRawData",
        "Photoshop",
        "image-resource",
    },
    {
        1032u,
        "GridGuidesInfo",
        "Photoshop",
        "image-resource",
    },
    {
        1033u,
        "ThumbnailResource",
        "Photoshop",
        "image-resource",
    },
    {
        1034u,
        "CopyrightFlag",
        "Photoshop",
        "image-resource",
    },
    {
        1035u,
        "URL",
        "Photoshop",
        "image-resource",
    },
    {
        1036u,
        "ThumbnailResource2",
        "Photoshop",
        "image-resource",
    },
    {
        1037u,
        "GlobalAngle",
        "Photoshop",
        "image-resource",
    },
    {
        1039u,
        "ICCProfile",
        "Photoshop",
        "image-resource",
    },
    {
        1040u,
        "Watermark",
        "Photoshop",
        "image-resource",
    },
    {
        1041u,
        "ICCUntagged",
        "Photoshop",
        "image-resource",
    },
    {
        1042u,
        "EffectsVisible",
        "Photoshop",
        "image-resource",
    },
    {
        1043u,
        "SpotHalftone",
        "Photoshop",
        "image-resource",
    },
    {
        1044u,
        "DocumentSpecificIDs",
        "Photoshop",
        "image-resource",
    },
    {
        1045u,
        "UnicodeAlphaNames",
        "Photoshop",
        "image-resource",
    },
    {
        1046u,
        "IndexedColorTableCount",
        "Photoshop",
        "image-resource",
    },
    {
        1047u,
        "TransparentIndex",
        "Photoshop",
        "image-resource",
    },
    {
        1049u,
        "GlobalAltitude",
        "Photoshop",
        "image-resource",
    },
    {
        1050u,
        "Slices",
        "Photoshop",
        "image-resource",
    },
    {
        1051u,
        "WorkflowURL",
        "Photoshop",
        "image-resource",
    },
    {
        1052u,
        "JumpToXPEP",
        "Photoshop",
        "image-resource",
    },
    {
        1053u,
        "AlphaIdentifiers",
        "Photoshop",
        "image-resource",
    },
    {
        1054u,
        "URLList",
        "Photoshop",
        "image-resource",
    },
    {
        1057u,
        "VersionInfo",
        "Photoshop",
        "image-resource",
    },
    {
        1058u,
        "EXIFData1",
        "Photoshop",
        "image-resource",
    },
    {
        1059u,
        "EXIFData3",
        "Photoshop",
        "image-resource",
    },
    {
        1060u,
        "XMPMetadata",
        "Photoshop",
        "image-resource",
    },
    {
        1061u,
        "CaptionDigest",
        "Photoshop",
        "image-resource",
    },
    {
        1062u,
        "PrintScale",
        "Photoshop",
        "image-resource",
    },
    {
        1064u,
        "PixelAspectRatio",
        "Photoshop",
        "image-resource",
    },
    {
        1065u,
        "LayerComps",
        "Photoshop",
        "image-resource",
    },
    {
        1069u,
        "LayerSelectionIDs",
        "Photoshop",
        "image-resource",
    },
    {
        1070u,
        "HDRToningInfo",
        "Photoshop",
        "image-resource",
    },
    {
        1071u,
        "PrintInfo",
        "Photoshop",
        "image-resource",
    },
    {
        1072u,
        "LayerGroupEnabledIDs",
        "Photoshop",
        "image-resource",
    },
    {
        1073u,
        "ColorSamplers",
        "Photoshop",
        "image-resource",
    },
    {
        1074u,
        "MeasurementScale",
        "Photoshop",
        "image-resource",
    },
    {
        1075u,
        "TimelineInformation",
        "Photoshop",
        "image-resource",
    },
    {
        1076u,
        "SheetDisclosure",
        "Photoshop",
        "image-resource",
    },
    {
        1077u,
        "DisplayInfoCS6",
        "Photoshop",
        "image-resource",
    },
    {
        1078u,
        "OnionSkins",
        "Photoshop",
        "image-resource",
    },
    {
        1080u,
        "CountInformation",
        "Photoshop",
        "image-resource",
    },
    {
        1082u,
        "PrintInformation",
        "Photoshop",
        "image-resource",
    },
    {
        1083u,
        "PrintStyle",
        "Photoshop",
        "image-resource",
    },
    {
        1084u,
        "MacNSPrintInfo",
        "Photoshop",
        "image-resource",
    },
    {
        1085u,
        "WindowsDEVMODE",
        "Photoshop",
        "image-resource",
    },
    {
        1086u,
        "AutoSaveFilePath",
        "Photoshop",
        "image-resource",
    },
    {
        1087u,
        "AutoSaveFormat",
        "Photoshop",
        "image-resource",
    },
    {
        1088u,
        "PathSelectionState",
        "Photoshop",
        "image-resource",
    },
};

typedef struct bk_chunk_registry_entry {
  char code[5];
  const char *name;
  const char *placement;
  uint32_t flags;
} bk_chunk_registry_entry;

static const bk_chunk_registry_entry png_registry[] = {
    {
        "IHDR",
        "IHDR chunk",
        "critical",
        1u,
    },
    {
        "PLTE",
        "PLTE chunk",
        "critical",
        1u,
    },
    {
        "IDAT",
        "IDAT chunk",
        "critical",
        1u,
    },
    {
        "IEND",
        "IEND chunk",
        "critical",
        1u,
    },
    {
        "tRNS",
        "tRNS chunk",
        "ancillary",
        0u,
    },
    {
        "gAMA",
        "gAMA chunk",
        "ancillary",
        0u,
    },
    {
        "cHRM",
        "cHRM chunk",
        "ancillary",
        0u,
    },
    {
        "sRGB",
        "sRGB chunk",
        "ancillary",
        0u,
    },
    {
        "iCCP",
        "iCCP chunk",
        "ancillary",
        0u,
    },
    {
        "tEXt",
        "tEXt chunk",
        "ancillary",
        0u,
    },
    {
        "zTXt",
        "zTXt chunk",
        "ancillary",
        0u,
    },
    {
        "iTXt",
        "iTXt chunk",
        "ancillary",
        0u,
    },
    {
        "bKGD",
        "bKGD chunk",
        "ancillary",
        0u,
    },
    {
        "pHYs",
        "pHYs chunk",
        "ancillary",
        0u,
    },
    {
        "sBIT",
        "sBIT chunk",
        "ancillary",
        0u,
    },
    {
        "sPLT",
        "sPLT chunk",
        "ancillary",
        0u,
    },
    {
        "hIST",
        "hIST chunk",
        "ancillary",
        0u,
    },
    {
        "tIME",
        "tIME chunk",
        "ancillary",
        0u,
    },
    {
        "eXIf",
        "eXIf chunk",
        "ancillary",
        0u,
    },
    {
        "acTL",
        "acTL chunk",
        "ancillary",
        0u,
    },
    {
        "fcTL",
        "fcTL chunk",
        "ancillary",
        0u,
    },
    {
        "fdAT",
        "fdAT chunk",
        "ancillary",
        0u,
    },
    {
        "oFFs",
        "oFFs chunk",
        "ancillary",
        0u,
    },
    {
        "pCAL",
        "pCAL chunk",
        "ancillary",
        0u,
    },
    {
        "sCAL",
        "sCAL chunk",
        "ancillary",
        0u,
    },
    {
        "gIFg",
        "gIFg chunk",
        "ancillary",
        0u,
    },
    {
        "gIFx",
        "gIFx chunk",
        "ancillary",
        0u,
    },
    {
        "vpAg",
        "vpAg chunk",
        "ancillary",
        0u,
    },
    {
        "caNv",
        "caNv chunk",
        "ancillary",
        0u,
    },
    {
        "orNT",
        "orNT chunk",
        "ancillary",
        0u,
    },
    {
        "pHYg",
        "pHYg chunk",
        "ancillary",
        0u,
    },
    {
        "sTER",
        "sTER chunk",
        "ancillary",
        0u,
    },
    {
        "dSIG",
        "dSIG chunk",
        "ancillary",
        0u,
    },
};

static const bk_tag_registry_entry jpeg_registry[] = {
    {
        0xc0u,
        "SOF0 Baseline",
        "JPEG",
        "marker",
    },
    {
        0xc1u,
        "SOF1 Extended sequential",
        "JPEG",
        "marker",
    },
    {
        0xc2u,
        "SOF2 Progressive",
        "JPEG",
        "marker",
    },
    {
        0xc3u,
        "SOF3 Lossless",
        "JPEG",
        "marker",
    },
    {
        0xc4u,
        "DHT",
        "JPEG",
        "marker",
    },
    {
        0xc5u,
        "SOF5 Differential sequential",
        "JPEG",
        "marker",
    },
    {
        0xc6u,
        "SOF6 Differential progressive",
        "JPEG",
        "marker",
    },
    {
        0xc7u,
        "SOF7 Differential lossless",
        "JPEG",
        "marker",
    },
    {
        0xc8u,
        "JPG extension",
        "JPEG",
        "marker",
    },
    {
        0xc9u,
        "SOF9 Arithmetic sequential",
        "JPEG",
        "marker",
    },
    {
        0xcau,
        "SOF10 Arithmetic progressive",
        "JPEG",
        "marker",
    },
    {
        0xcbu,
        "SOF11 Arithmetic lossless",
        "JPEG",
        "marker",
    },
    {
        0xccu,
        "DAC",
        "JPEG",
        "marker",
    },
    {
        0xcdu,
        "SOF13 Differential arithmetic",
        "JPEG",
        "marker",
    },
    {
        0xceu,
        "SOF14 Differential arithmetic progressive",
        "JPEG",
        "marker",
    },
    {
        0xcfu,
        "SOF15 Differential arithmetic lossless",
        "JPEG",
        "marker",
    },
    {
        0xd0u,
        "RST0",
        "JPEG",
        "marker",
    },
    {
        0xd1u,
        "RST1",
        "JPEG",
        "marker",
    },
    {
        0xd2u,
        "RST2",
        "JPEG",
        "marker",
    },
    {
        0xd3u,
        "RST3",
        "JPEG",
        "marker",
    },
    {
        0xd4u,
        "RST4",
        "JPEG",
        "marker",
    },
    {
        0xd5u,
        "RST5",
        "JPEG",
        "marker",
    },
    {
        0xd6u,
        "RST6",
        "JPEG",
        "marker",
    },
    {
        0xd7u,
        "RST7",
        "JPEG",
        "marker",
    },
    {
        0xd8u,
        "SOI",
        "JPEG",
        "marker",
    },
    {
        0xd9u,
        "EOI",
        "JPEG",
        "marker",
    },
    {
        0xdau,
        "SOS",
        "JPEG",
        "marker",
    },
    {
        0xdbu,
        "DQT",
        "JPEG",
        "marker",
    },
    {
        0xdcu,
        "DNL",
        "JPEG",
        "marker",
    },
    {
        0xddu,
        "DRI",
        "JPEG",
        "marker",
    },
    {
        0xdeu,
        "DHP",
        "JPEG",
        "marker",
    },
    {
        0xdfu,
        "EXP",
        "JPEG",
        "marker",
    },
    {
        0xe0u,
        "APP0 JFIF",
        "JPEG",
        "marker",
    },
    {
        0xe1u,
        "APP1 Exif/XMP",
        "JPEG",
        "marker",
    },
    {
        0xe2u,
        "APP2 ICC",
        "JPEG",
        "marker",
    },
    {
        0xe3u,
        "APP3",
        "JPEG",
        "marker",
    },
    {
        0xe4u,
        "APP4",
        "JPEG",
        "marker",
    },
    {
        0xe5u,
        "APP5",
        "JPEG",
        "marker",
    },
    {
        0xe6u,
        "APP6",
        "JPEG",
        "marker",
    },
    {
        0xe7u,
        "APP7",
        "JPEG",
        "marker",
    },
    {
        0xe8u,
        "APP8",
        "JPEG",
        "marker",
    },
    {
        0xe9u,
        "APP9",
        "JPEG",
        "marker",
    },
    {
        0xeau,
        "APP10",
        "JPEG",
        "marker",
    },
    {
        0xebu,
        "APP11",
        "JPEG",
        "marker",
    },
    {
        0xecu,
        "APP12",
        "JPEG",
        "marker",
    },
    {
        0xedu,
        "APP13 Photoshop",
        "JPEG",
        "marker",
    },
    {
        0xeeu,
        "APP14 Adobe",
        "JPEG",
        "marker",
    },
    {
        0xefu,
        "APP15",
        "JPEG",
        "marker",
    },
    {
        0xfeu,
        "COM",
        "JPEG",
        "marker",
    },
};

const char *bk_exif_registry_name(uint32_t code) {
  for (size_t i = 0; i < sizeof(exif_registry) / sizeof(exif_registry[0]);
       ++i) {
    if (exif_registry[i].code == code)
      return exif_registry[i].name;
  }
  return "Unknown EXIF tag";
}

const char *bk_photoshop_resource_name(uint32_t code) {
  for (size_t i = 0;
       i < sizeof(photoshop_registry) / sizeof(photoshop_registry[0]); ++i) {
    if (photoshop_registry[i].code == code)
      return photoshop_registry[i].name;
  }
  return "Unknown Photoshop resource";
}

const char *bk_jpeg_marker_name(uint32_t marker) {
  for (size_t i = 0; i < sizeof(jpeg_registry) / sizeof(jpeg_registry[0]);
       ++i) {
    if (jpeg_registry[i].code == marker)
      return jpeg_registry[i].name;
  }
  return "Unknown JPEG marker";
}

const char *bk_png_registered_chunk(const char code[4]) {
  if (!code)
    return NULL;
  for (size_t i = 0; i < sizeof(png_registry) / sizeof(png_registry[0]); ++i) {
    if (memcmp(png_registry[i].code, code, 4) == 0)
      return png_registry[i].name;
  }
  return NULL;
}

bk_status bk_tag_registry_dump_family(const char *family,
                                      bk_metadata *metadata) {
  char key[48];
  if (!family || !metadata)
    return BK_ERR_ARGUMENT;
  for (size_t i = 0; i < sizeof(exif_registry) / sizeof(exif_registry[0]);
       ++i) {
    if (strcmp(exif_registry[i].family, family) == 0) {
      snprintf(key, sizeof(key), "tag_%04x", exif_registry[i].code);
      if (bk_metadata_add(metadata, key, exif_registry[i].name) != BK_OK)
        return BK_ERR_LIMIT;
    }
  }
  return BK_OK;
}
